{% set name = "snowflake-connector-python" %}
{% set version = "2.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b064946dd9ffb0e1ffd3fc14682fad93604a041e43838851a0fe47efe4d6596e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vvv"
  entry_points:
    - snowflake-dump-ocsp-response = snowflake.connector.tool.dump_ocsp_response:main
    - snowflake-dump-ocsp-response-cache = snowflake.connector.tool.dump_ocsp_response_cache:main
    - snowflake-dump-certs = snowflake.connector.tool.dump_certs:main
    - snowflake-export-certs = snowflake.connector.tool.export_certs:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - azure-common <2.0.0
    - azure-storage-blob <12.0.0
    - boto3 >=1.4.4,<1.11.0
    - botocore >=1.5.0,<1.14.0
    - requests <2.23.0
    - urllib3 >=1.20,<1.26.0
    - certifi <2021.0.0
    - future <1.0.0
    - six <2.0.0
    - pytz <2021.0
    - pycryptodomex >=3.2,!=3.5.0,<4.0.0
    - pyOpenSSL >=16.2.0,<21.0.0
    - cffi >=1.9,<1.14
    - cryptography >=1.8.2,<3.0.0
    - ijson <3.0.0
    - pyjwt <2.0.0
    - idna <3.0.0
    - oscrypto <2.0.0
    - asn1crypto >0.24.0,<2.0.0
    - pyasn1 >=0.4.0,<0.5.0  # [py==27]
    - pyasn1-modules >=0.2.0,<0.3.0  # [py==27]
    - enum34  # [py==27]
    - keyring !=16.1.0   # [py3k]
    - pyarrow >=0.15.1,<0.16.0  # [py3k]
    - pandas <1.0.0  # [py3k]
    - pandas 0.24.2  # [py2k]
    
test:
  requires:
    - pip
  imports:
    - snowflake
    - snowflake.connector
  commands:
    - pip check

about:
  home: https://github.com/snowflakedb/snowflake-connector-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Snowflake Connector for Python'
  description: |
    The Snowflake Connector for Python provides an interface for 
    developing Python applications that can connect to Snowflake 
    and perform all standard operations. It provides a programming 
    alternative to developing applications in Java or C/C++ using 
    the Snowflake JDBC or ODBC drivers.
  doc_url: https://docs.snowflake.net/manuals/user-guide/python-connector.html
  dev_url: https://github.com/snowflakedb/snowflake-connector-python

extra:
  recipe-maintainers:
    - hajapy
    - talues
