{% set name = "snowflake-connector-python" %}
{% set version = "2.7.11" %}
{% set sha256 = "e577da63791dbd299629670b199510015361b5e863ff37e083224e39c2f9e73b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://codeload.github.com/snowflakedb/{{ name }}/tar.gz/v{{ version }}
  fn: {{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-drop-pyarrow-version-numbers.patch

build:
  number: 0
  # neither on Windows 32-bit nor on s390x there is right now arrow support
  skip: true  # [win32 or s390x or py<37]
  script:
    - export SF_NO_COPY_ARROW_LIB=1              # [unix]
    - export SF_ARROW_LIBDIR="${PREFIX}/lib"     # [unix]
    - export ENABLE_EXT_MODULES=true             # [unix]
    - set SF_NO_COPY_ARROW_LIB=1                 # [win]
    - set "SF_ARROW_LIBDIR=%PREFIX%\Library"     # [win]
    - set ENABLE_EXT_MODULES=1                   # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vvv
  entry_points:
    - snowflake-dump-ocsp-response = snowflake.connector.tool.dump_ocsp_response:main
    - snowflake-dump-ocsp-response-cache = snowflake.connector.tool.dump_ocsp_response_cache:main
    - snowflake-dump-certs = snowflake.connector.tool.dump_certs:main
    - snowflake-export-certs = snowflake.connector.tool.export_certs:main
  ignore_run_exports:
    - arrow-cpp

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - cython
    - arrow-cpp
    - pyarrow
    - numpy
    - setuptools >=40.6.0
    - wheel
  run:
    - python
    - {{ pin_compatible('arrow-cpp', max_pin='x') }}
    # While requests is vendored, we use regular requests to perform OCSP checks
    - asn1crypto >0.24.0,<2.0.0
    - cffi >=1.9,<2.0.0
    - cryptography >=3.1.0,<37.0.0
    - oscrypto <2.0.0
    - pyopenssl >=16.2.0,<23.0.0
    - pycryptodomex >=3.2,!=3.5.0,<4.0.0
    - pyjwt <3.0.0
    - pytz
    - requests <3.0.0
    # A functioning pkg_resources.working_set.by_key and pkg_resources.Requirement is
    # required. Python 3.6 was released at the end of 2016. setuptools 34.0.0 was released
    # in early 2017, so we pick this version as a reasonably modern base.
    - setuptools >34.0.0
    # requests requirements
    - charset-normalizer ~=2.0.0
    - idna >=2.5,<4
    - urllib3 >=1.21.1,<1.27
    - certifi >=2017.4.17
    - typing_extensions >=4.3,<5
  run_constrained:
    - pandas >1,<1.5
    - {{ pin_compatible('pyarrow', max_pin='x') }}
    - keyring !=16.1.0,<24.0.0

test:
  requires:
    - pip
  imports:
    - snowflake
    - snowflake.connector
    - snowflake.connector.arrow_iterator
  commands:
    - pip check || true  # [not win]
    - pip check || 1  # [win]

about:
  home: https://github.com/snowflakedb/snowflake-connector-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Snowflake Connector for Python
  description: |
    The Snowflake Connector for Python provides an interface for
    developing Python applications that can connect to Snowflake
    and perform all standard operations. It provides a programming
    alternative to developing applications in Java or C/C++ using
    the Snowflake JDBC or ODBC drivers.
  doc_url: https://docs.snowflake.net/manuals/user-guide/python-connector.html
  dev_url: https://github.com/snowflakedb/snowflake-connector-python

extra:
  recipe-maintainers:
    - hajapy
    - talues
    - xhochy
    - mariusvniekerk
    - fhoehle
