{% set name = "snowflake-connector-python" %}
{% set version = "3.0.3" %}
{% set sha256 = "bc95fd0e78287d4b16b19f48d936efca75c40833154ec919514d92d460efd532" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://codeload.github.com/snowflakedb/{{ name }}/tar.gz/v{{ version }}
  fn: {{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-drop-pyarrow-versions-build-with-proper-ABI-settings.patch
    - 0002-Make-code-compatible-with-older-pyarrow-versions.patch
    - 0003-Remove-conflicting-Windows-macro.patch

build:
  number: 0
  # no arrow support on win-32 or s390x
  skip: true  # [win32 or s390x or py<37]
  script:
    - export SF_NO_COPY_ARROW_LIB=1              # [unix]
    - export SF_ARROW_LIBDIR="${PREFIX}/lib"     # [unix]
    - export ENABLE_EXT_MODULES=true             # [unix]
    - set SF_NO_COPY_ARROW_LIB=1                 # [win]
    - set "SF_ARROW_LIBDIR=%PREFIX%\Library"     # [win]
    - set ENABLE_EXT_MODULES=1                   # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vvv --no-build-isolation --no-deps
  entry_points:
    - snowflake-dump-ocsp-response = snowflake.connector.tool.dump_ocsp_response:main
    - snowflake-dump-ocsp-response-cache = snowflake.connector.tool.dump_ocsp_response_cache:main
    - snowflake-dump-certs = snowflake.connector.tool.dump_certs:main
    - snowflake-export-certs = snowflake.connector.tool.export_certs:main
  ignore_run_exports:
    - arrow-cpp

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - cython
    - arrow-cpp >=10,<11
    - pyarrow
    - numpy
    - setuptools >=40.6.0
    - wheel
  run:
    - python
    - packaging
    - pyarrow
    - {{ pin_compatible('arrow-cpp', max_pin='x') }}
    - asn1crypto >0.24.0,<2.0.0
    - cffi >=1.9,<2.0.0
    - cryptography >=3.1.0,<41.0.0
    - oscrypto <2.0.0
    - pyopenssl >=16.2.0,<24.0.0
    - pycryptodomex >=3.2,!=3.5.0,<4.0.0
    - pyjwt <3.0.0
    - pytz
    - requests <3.0.0
    - charset-normalizer >=2,<3
    - idna >=2.5,<4
    - urllib3 >=1.21.1,<1.27
    - certifi >=2017.4.17
    - typing-extensions >=4.3.0,<5
    - filelock>=3.5,<4
  run_constrained:
    - pandas >1,<1.6
    - keyring !=16.1.0,<24.0.0

test:
  requires:
    - pip
  imports:
    - snowflake
    - snowflake.connector
    - snowflake.connector.arrow_iterator
  commands:
    - pip check

about:
  home: https://github.com/snowflakedb/snowflake-connector-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Snowflake Connector for Python
  description: |
    The Snowflake Connector for Python provides an interface for
    developing Python applications that can connect to Snowflake
    and perform all standard operations. It provides a programming
    alternative to developing applications in Java or C/C++ using
    the Snowflake JDBC or ODBC drivers.
  doc_url: https://docs.snowflake.net/manuals/user-guide/python-connector.html
  dev_url: https://github.com/snowflakedb/snowflake-connector-python

extra:
  recipe-maintainers:
    - hajapy
    - talues
    - xhochy
    - mariusvniekerk
    - fhoehle
