{% set name = "snowflake-connector-python" %}
{% set version = "3.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/snowflakedb/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 695992d4540379a8f3a8d3157eadecf3a5fe606e85c424a3080b10b93a3c429c
  
build:
  number: 0
  # s390x not needed for snowflake
  skip: true  # [s390x or py<38]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - snowflake-dump-ocsp-response = snowflake.connector.tool.dump_ocsp_response:main
    - snowflake-dump-ocsp-response-cache = snowflake.connector.tool.dump_ocsp_response_cache:main
    - snowflake-dump-certs = snowflake.connector.tool.dump_certs:main
    - snowflake-export-certs = snowflake.connector.tool.export_certs:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - setuptools
    - wheel
  run:
    - python
    - asn1crypto >0.24.0,<2.0.0
    - cffi >=1.9,<2.0.0
    - cryptography >=3.1.0,<43.0.0
    - pyopenssl >=16.2.0,<25.0.0
    - pyjwt <3.0.0
    - pytz
    - requests <3.0.0
    - importlib-metadata  # [py<38]
    - packaging
    - charset-normalizer >=2,<4
    - idna >=2.5,<4
    - urllib3 >=1.21.1,<2.0.0  # [py<310]
    - certifi >=2017.4.17
    - typing-extensions >=4.3,<5
    - filelock >=3.5,<4
    - sortedcontainers >=2.4.0
    - platformdirs >=2.6.0,<5.0.0
    - tomlkit
  run_constrained:
    - pandas >=1.0.0,<3.0.0
    - keyring >=23.1.0,<25.0.0

# ignore these unit tests because they use relative imports
# or not found modules (existing but not well configured).
{% set tests_to_ignore = " --ignore=test/unit/test_configmanager.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=test/unit/test_connection.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=test/unit/test_encryption_util.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=test/unit/test_error_arrow_stream.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=test/unit/test_result_batch.py" %}
{% set tests_to_ignore = tests_to_ignore + " --ignore=test/unit/test_s3_util.py" %}
# ignore this test because it takes a lot (retry/timeout network tests)
{% set tests_to_ignore = tests_to_ignore + " --ignore=test/unit/test_retry_network.py" %}

{% set tests_to_deselect = "" %}
# linux: deselect the following tests because file permissions 
# will not be set correctly and fail with DID NOT RAISE PermissionError
{% set tests_to_deselect = tests_to_deselect + " --deselect=test/unit/test_cache.py::TestSFDictFileCache::test_read_only" %}        # [linux]
{% set tests_to_deselect = tests_to_deselect + " --deselect=test/unit/test_easy_logging.py::test_config_file_inaccessible_path" %}  # [linux]
{% set tests_to_deselect = tests_to_deselect + " --deselect=test/unit/test_put_get.py::test_put_error" %}                           # [linux]

test:
  imports:
    - snowflake
    - snowflake.connector
    - snowflake.connector.nanoarrow_arrow_iterator
  requires:
    - pip
    - pytest
  source_files:
    - test/unit
    - test/data/cert_tests/incomplete-chain.pem
  commands:
    - pip check
    - pytest -v test/unit {{ tests_to_ignore }} {{ tests_to_deselect }}

about:
  home: https://github.com/snowflakedb/snowflake-connector-python
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.txt
    - NOTICE
  summary: Snowflake Connector for Python
  description: |
    The Snowflake Connector for Python provides an interface for
    developing Python applications that can connect to Snowflake
    and perform all standard operations. It provides a programming
    alternative to developing applications in Java or C/C++ using
    the Snowflake JDBC or ODBC drivers.
  doc_url: https://docs.snowflake.net/manuals/user-guide/python-connector.html
  dev_url: https://github.com/snowflakedb/snowflake-connector-python

extra:
  recipe-maintainers:
    - hajapy
    - talues
    - xhochy
    - mariusvniekerk
    - fhoehle
