# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.15
  strategy:
    matrix:
      osx_64_arrow_cpp3.0.0numpy1.17python3.6.____cpython:
        CONFIG: osx_64_arrow_cpp3.0.0numpy1.17python3.6.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp3.0.0numpy1.17pytho_ha73c33efff
      osx_64_arrow_cpp3.0.0numpy1.17python3.7.____cpython:
        CONFIG: osx_64_arrow_cpp3.0.0numpy1.17python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp3.0.0numpy1.17pytho_h51c20c3756
      osx_64_arrow_cpp3.0.0numpy1.17python3.8.____cpython:
        CONFIG: osx_64_arrow_cpp3.0.0numpy1.17python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp3.0.0numpy1.17pytho_h63eb43df74
      osx_64_arrow_cpp3.0.0numpy1.19python3.9.____cpython:
        CONFIG: osx_64_arrow_cpp3.0.0numpy1.19python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp3.0.0numpy1.19pytho_h54ad1d6ace
      osx_64_arrow_cpp4.0.0numpy1.17python3.6.____cpython:
        CONFIG: osx_64_arrow_cpp4.0.0numpy1.17python3.6.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp4.0.0numpy1.17pytho_hfc2fba931f
      osx_64_arrow_cpp4.0.0numpy1.17python3.7.____cpython:
        CONFIG: osx_64_arrow_cpp4.0.0numpy1.17python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp4.0.0numpy1.17pytho_h98459b2c06
      osx_64_arrow_cpp4.0.0numpy1.17python3.8.____cpython:
        CONFIG: osx_64_arrow_cpp4.0.0numpy1.17python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp4.0.0numpy1.17pytho_hcc158f448b
      osx_64_arrow_cpp4.0.0numpy1.19python3.9.____cpython:
        CONFIG: osx_64_arrow_cpp4.0.0numpy1.19python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp4.0.0numpy1.19pytho_h879ad5af3f
      osx_64_arrow_cpp4.0.1numpy1.17python3.6.____cpython:
        CONFIG: osx_64_arrow_cpp4.0.1numpy1.17python3.6.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp4.0.1numpy1.17pytho_hcd838faada
      osx_64_arrow_cpp4.0.1numpy1.17python3.7.____cpython:
        CONFIG: osx_64_arrow_cpp4.0.1numpy1.17python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp4.0.1numpy1.17pytho_h43e1e9600a
      osx_64_arrow_cpp4.0.1numpy1.17python3.8.____cpython:
        CONFIG: osx_64_arrow_cpp4.0.1numpy1.17python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp4.0.1numpy1.17pytho_he6768eb5f5
      osx_64_arrow_cpp4.0.1numpy1.19python3.9.____cpython:
        CONFIG: osx_64_arrow_cpp4.0.1numpy1.19python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp4.0.1numpy1.19pytho_h4844b8cecf
      osx_arm64_arrow_cpp3.0.0python3.8.____cpython:
        CONFIG: osx_arm64_arrow_cpp3.0.0python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_arm64_arrow_cpp3.0.0python3.8.____cpython
      osx_arm64_arrow_cpp3.0.0python3.9.____cpython:
        CONFIG: osx_arm64_arrow_cpp3.0.0python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_arm64_arrow_cpp3.0.0python3.9.____cpython
      osx_arm64_arrow_cpp4.0.0python3.8.____cpython:
        CONFIG: osx_arm64_arrow_cpp4.0.0python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_arm64_arrow_cpp4.0.0python3.8.____cpython
      osx_arm64_arrow_cpp4.0.0python3.9.____cpython:
        CONFIG: osx_arm64_arrow_cpp4.0.0python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_arm64_arrow_cpp4.0.0python3.9.____cpython
      osx_arm64_arrow_cpp4.0.1python3.8.____cpython:
        CONFIG: osx_arm64_arrow_cpp4.0.1python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_arm64_arrow_cpp4.0.1python3.8.____cpython
      osx_arm64_arrow_cpp4.0.1python3.9.____cpython:
        CONFIG: osx_arm64_arrow_cpp4.0.1python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_arm64_arrow_cpp4.0.1python3.9.____cpython
  timeoutInMinutes: 360

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
  - script: |
        artifact_name="conda_artifacts_$(build.BuildId)_$(SHORT_CONFIG_NAME)"
        echo "##vso[task.setVariable variable=ARTIFACT_NAME]$artifact_name"
        if [ -d /Users/runner/miniforge3/conda-bld/ ]; then
          echo "##vso[task.setVariable variable=CONDA_BLD_DIR_EXISTS]true"
        fi
    displayName: Check for conda build artifacts
    condition: succeededOrFailed()

  - publish: /Users/runner/miniforge3/conda-bld/
    artifact: $(ARTIFACT_NAME)
    condition: eq(variables.CONDA_BLD_DIR_EXISTS, 'true')