# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.15
  strategy:
    matrix:
      osx_64_arrow_cpp4.0.0numpy1.18python3.6.____cpython:
        CONFIG: osx_64_arrow_cpp4.0.0numpy1.18python3.6.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp4.0.0numpy1.18pytho_hb8e58a0b0f
      osx_64_arrow_cpp4.0.0numpy1.18python3.7.____cpython:
        CONFIG: osx_64_arrow_cpp4.0.0numpy1.18python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp4.0.0numpy1.18pytho_h2bdb35c26e
      osx_64_arrow_cpp4.0.0numpy1.18python3.8.____cpython:
        CONFIG: osx_64_arrow_cpp4.0.0numpy1.18python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp4.0.0numpy1.18pytho_hc6d018a660
      osx_64_arrow_cpp4.0.0numpy1.19python3.9.____cpython:
        CONFIG: osx_64_arrow_cpp4.0.0numpy1.19python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp4.0.0numpy1.19pytho_h879ad5af3f
      osx_64_arrow_cpp4.0.1numpy1.18python3.6.____cpython:
        CONFIG: osx_64_arrow_cpp4.0.1numpy1.18python3.6.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp4.0.1numpy1.18pytho_h16d71efa90
      osx_64_arrow_cpp4.0.1numpy1.18python3.7.____cpython:
        CONFIG: osx_64_arrow_cpp4.0.1numpy1.18python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp4.0.1numpy1.18pytho_hb9d2d38b65
      osx_64_arrow_cpp4.0.1numpy1.18python3.8.____cpython:
        CONFIG: osx_64_arrow_cpp4.0.1numpy1.18python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp4.0.1numpy1.18pytho_h02f3b7108d
      osx_64_arrow_cpp4.0.1numpy1.19python3.9.____cpython:
        CONFIG: osx_64_arrow_cpp4.0.1numpy1.19python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp4.0.1numpy1.19pytho_h4844b8cecf
      osx_64_arrow_cpp5.0.0numpy1.18python3.6.____cpython:
        CONFIG: osx_64_arrow_cpp5.0.0numpy1.18python3.6.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp5.0.0numpy1.18pytho_hf85bac346c
      osx_64_arrow_cpp5.0.0numpy1.18python3.7.____cpython:
        CONFIG: osx_64_arrow_cpp5.0.0numpy1.18python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp5.0.0numpy1.18pytho_hfec9e762b1
      osx_64_arrow_cpp5.0.0numpy1.18python3.8.____cpython:
        CONFIG: osx_64_arrow_cpp5.0.0numpy1.18python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp5.0.0numpy1.18pytho_h685fbb5742
      osx_64_arrow_cpp5.0.0numpy1.19python3.9.____cpython:
        CONFIG: osx_64_arrow_cpp5.0.0numpy1.19python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_64_arrow_cpp5.0.0numpy1.19pytho_h0b7cd744bf
      osx_arm64_arrow_cpp4.0.0python3.8.____cpython:
        CONFIG: osx_arm64_arrow_cpp4.0.0python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_arm64_arrow_cpp4.0.0python3.8.____cpython
      osx_arm64_arrow_cpp4.0.0python3.9.____cpython:
        CONFIG: osx_arm64_arrow_cpp4.0.0python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_arm64_arrow_cpp4.0.0python3.9.____cpython
      osx_arm64_arrow_cpp4.0.1python3.8.____cpython:
        CONFIG: osx_arm64_arrow_cpp4.0.1python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_arm64_arrow_cpp4.0.1python3.8.____cpython
      osx_arm64_arrow_cpp4.0.1python3.9.____cpython:
        CONFIG: osx_arm64_arrow_cpp4.0.1python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_arm64_arrow_cpp4.0.1python3.9.____cpython
      osx_arm64_arrow_cpp5.0.0python3.8.____cpython:
        CONFIG: osx_arm64_arrow_cpp5.0.0python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_arm64_arrow_cpp5.0.0python3.8.____cpython
      osx_arm64_arrow_cpp5.0.0python3.9.____cpython:
        CONFIG: osx_arm64_arrow_cpp5.0.0python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG_NAME: osx_arm64_arrow_cpp5.0.0python3.9.____cpython
    maxParallel: 17
  timeoutInMinutes: 360

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
  - script: |
        artifact_name="conda_artifacts_$(build.BuildId)_$(SHORT_CONFIG_NAME)"
        echo "##vso[task.setVariable variable=ARTIFACT_NAME]$artifact_name"
        if [ -d /Users/runner/miniforge3/conda-bld/ ]; then
          echo "##vso[task.setVariable variable=CONDA_BLD_DIR_EXISTS]true"
        fi
    displayName: Check for conda build artifacts
    condition: succeededOrFailed()

  - publish: /Users/runner/miniforge3/conda-bld/
    artifact: $(ARTIFACT_NAME)
    condition: eq(variables.CONDA_BLD_DIR_EXISTS, 'true')