# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux_64_arrow_cpp4.0.0numpy1.18python3.6.____cpython:
        CONFIG: linux_64_arrow_cpp4.0.0numpy1.18python3.6.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_64_arrow_cpp4.0.0numpy1.18pyt_h97f8f84677
      linux_64_arrow_cpp4.0.0numpy1.18python3.7.____cpython:
        CONFIG: linux_64_arrow_cpp4.0.0numpy1.18python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_64_arrow_cpp4.0.0numpy1.18pyt_h1926fe984f
      linux_64_arrow_cpp4.0.0numpy1.18python3.8.____cpython:
        CONFIG: linux_64_arrow_cpp4.0.0numpy1.18python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_64_arrow_cpp4.0.0numpy1.18pyt_h735e00ad50
      linux_64_arrow_cpp4.0.0numpy1.19python3.9.____cpython:
        CONFIG: linux_64_arrow_cpp4.0.0numpy1.19python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_64_arrow_cpp4.0.0numpy1.19pyt_h3f10d0132e
      linux_64_arrow_cpp4.0.1numpy1.18python3.6.____cpython:
        CONFIG: linux_64_arrow_cpp4.0.1numpy1.18python3.6.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_64_arrow_cpp4.0.1numpy1.18pyt_he62b352172
      linux_64_arrow_cpp4.0.1numpy1.18python3.7.____cpython:
        CONFIG: linux_64_arrow_cpp4.0.1numpy1.18python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_64_arrow_cpp4.0.1numpy1.18pyt_h0de1cab995
      linux_64_arrow_cpp4.0.1numpy1.18python3.8.____cpython:
        CONFIG: linux_64_arrow_cpp4.0.1numpy1.18python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_64_arrow_cpp4.0.1numpy1.18pyt_h9ab0c3170a
      linux_64_arrow_cpp4.0.1numpy1.19python3.9.____cpython:
        CONFIG: linux_64_arrow_cpp4.0.1numpy1.19python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_64_arrow_cpp4.0.1numpy1.19pyt_h2b0502c619
      linux_64_arrow_cpp5.0.0numpy1.18python3.6.____cpython:
        CONFIG: linux_64_arrow_cpp5.0.0numpy1.18python3.6.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_64_arrow_cpp5.0.0numpy1.18pyt_h60b1336373
      linux_64_arrow_cpp5.0.0numpy1.18python3.7.____cpython:
        CONFIG: linux_64_arrow_cpp5.0.0numpy1.18python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_64_arrow_cpp5.0.0numpy1.18pyt_h13544d08ae
      linux_64_arrow_cpp5.0.0numpy1.18python3.8.____cpython:
        CONFIG: linux_64_arrow_cpp5.0.0numpy1.18python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_64_arrow_cpp5.0.0numpy1.18pyt_ha64cafa2b5
      linux_64_arrow_cpp5.0.0numpy1.19python3.9.____cpython:
        CONFIG: linux_64_arrow_cpp5.0.0numpy1.19python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_64_arrow_cpp5.0.0numpy1.19pyt_h03c3cd4d09
      linux_ppc64le_arrow_cpp4.0.0numpy1.18python3.6.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp4.0.0numpy1.18python3.6.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_ppc64le_arrow_cpp4.0.0numpy1._h86fcfb2ff2
      linux_ppc64le_arrow_cpp4.0.0numpy1.18python3.7.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp4.0.0numpy1.18python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_ppc64le_arrow_cpp4.0.0numpy1._h2d9915d5f6
      linux_ppc64le_arrow_cpp4.0.0numpy1.18python3.8.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp4.0.0numpy1.18python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_ppc64le_arrow_cpp4.0.0numpy1._h4a6938ed08
      linux_ppc64le_arrow_cpp4.0.0numpy1.19python3.9.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp4.0.0numpy1.19python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_ppc64le_arrow_cpp4.0.0numpy1._he43bfd9efc
      linux_ppc64le_arrow_cpp4.0.1numpy1.18python3.6.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp4.0.1numpy1.18python3.6.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_ppc64le_arrow_cpp4.0.1numpy1._h279098952a
      linux_ppc64le_arrow_cpp4.0.1numpy1.18python3.7.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp4.0.1numpy1.18python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_ppc64le_arrow_cpp4.0.1numpy1._h84550abe3c
      linux_ppc64le_arrow_cpp4.0.1numpy1.18python3.8.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp4.0.1numpy1.18python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_ppc64le_arrow_cpp4.0.1numpy1._hb9c2773f68
      linux_ppc64le_arrow_cpp4.0.1numpy1.19python3.9.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp4.0.1numpy1.19python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_ppc64le_arrow_cpp4.0.1numpy1._hd0e80da0f5
      linux_ppc64le_arrow_cpp5.0.0numpy1.18python3.6.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp5.0.0numpy1.18python3.6.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_ppc64le_arrow_cpp5.0.0numpy1._hb4517d62bb
      linux_ppc64le_arrow_cpp5.0.0numpy1.18python3.7.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp5.0.0numpy1.18python3.7.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_ppc64le_arrow_cpp5.0.0numpy1._hab6de30014
      linux_ppc64le_arrow_cpp5.0.0numpy1.18python3.8.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp5.0.0numpy1.18python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_ppc64le_arrow_cpp5.0.0numpy1._h5564c32155
      linux_ppc64le_arrow_cpp5.0.0numpy1.19python3.9.____cpython:
        CONFIG: linux_ppc64le_arrow_cpp5.0.0numpy1.19python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
        SHORT_CONFIG_NAME: linux_ppc64le_arrow_cpp5.0.0numpy1._h798ff4eb10
    maxParallel: 22
  timeoutInMinutes: 360

  steps:
  - script: |
         rm -rf /opt/ghc
         df -h
    displayName: Manage disk space

  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
  - script: |
        artifact_name="conda_artifacts_$(build.BuildId)_$(SHORT_CONFIG_NAME)"
        echo "##vso[task.setVariable variable=ARTIFACT_NAME]$artifact_name"
        if [ -d build_artifacts ]; then
          echo "##vso[task.setVariable variable=CONDA_BLD_DIR_EXISTS]true"
        fi
    displayName: Check for conda build artifacts
    condition: succeededOrFailed()

  - publish: build_artifacts/
    artifact: $(ARTIFACT_NAME)
    condition: eq(variables.CONDA_BLD_DIR_EXISTS, 'true')